# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djmy_EwpmjfynzCx7b9ngwhLxI2YFxHZ

**Market basket analysis**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pip install apyori

from apyori import apriori

dataset = pd.read_csv('Market_Basket_Optimisation.csv',header=None)

dataset.head()

dataset.shape

transactions = []
for i in range(0,7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

rules = apriori(transactions, min_support=0.003, min_confidence=0.2, min_lift=3, min_length=2)

print(list(rules))

"""RelationRecord(items=frozenset({'avocado', 'spaghetti', 'milk'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'avocado', 'spaghetti'}), items_add=frozenset({'milk'}), confidence=0.41666666666666663, lift=3.215449245541838)])

The support value for this rule is 0.003. This number is calculated by dividing the number of transactions containing ‘avocado,’ ‘spaghetti,’ and ‘milk’ by the total number of transactions.

The confidence level for the rule is 0.416, which shows that out of all the transactions that contain both ‘avocado’ and ‘spaghetti’, 41.6 percent contain ‘milk’ too.

The lift of 1.241 tells us that ‘milk’ is 1.241 times more likely to be bought by the customers who buy both ‘avocado’ and ‘spaghetti’ compared to the default likelihood sale of ‘milk.’

**conclusion**

Market Basket Analysis is applicable in many other areas:

In the manufacturing industry for predictive analysis of equipment failure.
In Pharmaceutical/Bioinformatics for the discovery of co-occurrence relationships among diagnosis and pharmaceutical active ingredients prescribed to different patient groups.
In Banking/Criminology for fraud detection based on credit card usage data.
For analyzing customer behavior by associating purchases with demographic and socio-economic data.
More and more organizations are discovering ways of using market basket analysis to gain useful insights into associations and hidden relationships. As industry leaders continue to explore the technique’s value, a predictive version of market basket analysis is making in-roads across many sectors in an effort to identify sequential purchases.
"""

